spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: event-service
          uri: lb://EVENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/events/**
        - id: approval-service
          uri: lb://APPROVAL-SERVICE
          predicates:
            - Path=/api/approval/**
        - id: event-search-service
          uri: lb://EVENT-SEARCH-SERVICE
          predicates:
            - Path=/search/**

jwt:
  secret: OQqAf7yZmXVoD0idFdFdgDgfFgKHgAsjFlUFfgTfhY9TjPz8rZwYjRidFdDefFDhNsfKKzM0uM5O6MvFo

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
