services:
  postgres:
    image: postgres:latest
    container_name: auth_service_db
    restart: always
    environment:
      POSTGRES_USER: beko
      POSTGRES_PASSWORD: beko
      POSTGRES_DB: auth_service_db
    ports:
      - "5433:5432"
